config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  root 'main#index'

  get 'search-anything' => 'search#autocomplete'
  get 'promotions', to: redirect('offers')

  draw :orders
  draw :brands
  draw :special_products
  draw :feedback
  draw :articles

  resources :category, only: [], param: :slug do
    resources :offers, only: :index
  end
  resources :offers, only: :index
  resources :availability_subscribers, only: :create

  namespace :admin do
    root 'main#index', as: 'root' # see https://github.com/rails/rails/pull/23235

    draw :admin_concerns
    draw :admin_categories
    draw :admin_products
    draw :admin_related_pages
    draw :admin_articles
    draw :admin_sync
    draw :admin_settings

    resources :brands
    resources :orders, only: [:index, :show, :update]
    resources :suborders, only: :update

    get 'search-products.json' => 'search#autocomplete', format: :json, as: 'search_products'
  end

  draw :pages
end

app/models/order.rb
class Order < ApplicationRecord
  include OrderObserver
  include ActionView::Helpers::NumberHelper

  LIQPAY_COMMISSION     = 0.5/100
  NOVAPOSHTA_COMMISSION = 2.0/100

  belongs_to :user
  has_many   :suborders, dependent: :destroy do
    def <<(suborder)
      suborder_with_same_variant = proxy_association.owner.suborders.find do |s|
        s.variant == suborder.variant
      end
      super unless suborder_with_same_variant
      proxy_association.owner.validate
    end
  end
  has_many :payments

  attr_accessor :delivery_method, :delivery_info, :address

  enum payment_method:  [:cash_to_courier, :cash_on_delivery, :liqpay]
  enum status:          [:placed, :pending, :paid, :refunded]
  enum delivery_method: [:address, :novaposhta]

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :suborders
  accepts_nested_attributes_for :payments

  validates_numericality_of :total_correction

  before_validation    :setup_user_validation, on: :create
  validates_associated :suborders
  after_validation     :calculate_commission, :calculate_total
  before_create        :save_user, :add_delivery_info_to_notes
  before_save          :check_for_suborders

  default_scope -> { order(created_at: :desc) }

  def suborders= suborders
    suborders_to_write = []
    suborders.each do |suborder|
      suborder_with_same_variant = suborders_to_write.find do |s|
        s.variant == suborder.variant
      end
      suborders_to_write << suborder unless suborder_with_same_variant
    end
    association(:suborders).writer suborders_to_write
    validate
  end

  def autosave_associated_records_for_user
    if user
      self[:user_phone] = user.phone if self[:user_phone].blank?
      self[:user_name]  = user.name if self[:user_name].blank?
      if user.email.present?
        User.find_by(email: user.email).try(:tap) { |u| self.user = u }
      end
    end
  end

  def number
    id.to_s
  end

  def size
    valid_suborders.inject(0) { |size, suborder| size + suborder.quantity }
  end

  def original_total
    valid_suborders.inject(0) do |total, suborder|
      total + suborder.total
    end
  end

  def remove_suborder(index)
    self.suborders = suborders.to_a.tap { |s| s.delete_at(index) }
  end

  def update_suborder(index, quantity)
    suborders[index].try { |s| s.quantity = quantity }
    calculate_total
  end

  def total_with_currency
    number_to_currency total
  end

  def description
    suborders.map(&:title).join(", ")
  end

  def valid_suborders
    suborders.select(&:valid?)
  end

  def free_ship?
    valid_suborders.map { |s| s.variant.product.free_ship?  }.uniq == [true]
  end

  alias_method :free_ship, :free_ship?

  private

  def setup_user_validation
    if user
      user.disable_email_uniqueness = true
      user.required_email = true if liqpay?
    end
  end

  def save_user
    user.save
    # its very strange... why rails does not do this automaticaly?
    self.user_id = user.id
  end

  def check_for_suborders
    throw(:abort) unless suborders.any?
  end

  def add_delivery_info_to_notes
    self[:notes] ||= ''
    self[:notes] << "\nДоставка: "
    if delivery_method.present?
      self[:notes] << I18n.t(
        "activerecord.attributes.order.delivery_method.#{delivery_method}"
      )
    else
      self[:notes] << "не указано"
    end
    self[:notes] << " #{delivery_info}"
    self[:notes] << " #{address}"
  end

  def calculate_total
    self[:total] = original_total + total_correction + commission
  end

  def calculate_commission
    self[:commission] = 0
    if total
      self[:commission] = total * LIQPAY_COMMISSION if liqpay?
      self[:commission] = total * NOVAPOSHTA_COMMISSION + 20 if cash_on_delivery?
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  helper_method :filter_params

  def index
    @orders = Order.where(orders_where_condition).page(params[:page])
  end

  def show
    @order = Order.includes(:suborders).find params[:id]
  end

  def update
    order = Order.find params[:id]
    order.update! order_params
    redirect_to [:admin, order]
  end

  private

  def filter_params(filter)
    params.except(:action, :controller).permit!.merge(filter)
  end

  def orders_where_condition
    condition = {}
    %w(payment_method status).each do |name|
      # TODO: replace by "payment_method: params[:payment_method]"
      condition[name] = Order.send(name.pluralize)[params[name]] if params[name]
    end
    condition
  end

  def order_params
    params.require(:order).permit(:status, :total_correction)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :reject_spam

  def create
    cart.attributes = order_params
    respond_to do |format|
      if cart.save
        message = render_to_string(
          partial: 'success.html', locals: { order: cart }
        )
        format.json do
          render json: cart.as_json.merge(flash: message), status: :created
          reset_cart
        end
      else
        format.json { render json: cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def pay
    @order = Order.pending.find_by! uuid: params[:uuid]
    options = {
      version: "3",
      amount: @order.total,
      currency: "UAH",
      description: @order.description,
      order_id: @order.number,
      server_url: order_api_callback_url
    }
    options[:sandbox] = 1 if Settings.liqpay.sandbox
    @pay_button = liqpay.cnb_form options
  end

  def api_callback
    request = Service::Liqpay::Request.new liqpay, params[:data]
    if request.valid?(params[:signature])
      data = request.data
      order = Order.pending.find data['order_id']

      order.payments_attributes = [{
        amount:          data['amount'],
        transaction_uid: data['transaction_id'],
        account:         data['sender_phone'],
        status:          data['status']
      }]
      order.status = :paid if request.success?
      order.save!

      ManagerMailer.order_payment(order, data['transaction_id'])
                   .deliver_later unless request.success?

      head :ok
    else
      head :bad_request
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :notes, :payment_method, :delivery_info, :delivery_method, :address,
      user_attributes: [:first_name, :last_name, :email, :phone, :subscribed]
    )
  end

  def reject_spam
    head :ok, status: 403 if params[:text].present?
  end

  def liqpay
    @liqpay ||= Liqpay.new(
      Rails.application.secrets.liqpay.to_hash.symbolize_keys
    )
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

  def order_status(order)
    labels = {
      placed: 'info',
      pending: 'primary',
      paid: 'success',
      refunded: 'default'
    }
    render 'status', order: order, label: labels.fetch(order.status.to_sym, 'info')
  end

  def order_payment_method(order)
    return unless order.payment_method
    labels = {}
    render 'payment_method', order: order, label: labels.fetch(order.payment_method.to_sym, 'info')
  end
end

app/views/admin/orders/_payment_method.html.slim
span.label.label-info => t("activerecord.attributes.order.payment_method.#{order.payment_method}")

app/views/admin/orders/_status.html.slim
span.label class="label-#{label}" = t("activerecord.attributes.order.status.#{order.status}")

app/views/admin/orders/index.html.slim
= render layout: 'boxed', locals: {title: 'Заказы'} do

  .orders-filters
    = link_to "все", admin_orders_path, class: "btn btn-default#{' active' unless params[:payment_method] || params[:status]}"
    .btn-group
      - Order.payment_methods.keys.each do |payment_method|
        = link_to t("activerecord.attributes.order.payment_method.#{payment_method}"), admin_orders_path(filter_params(payment_method: payment_method)), class: "btn btn-default#{' active' if params[:payment_method] == payment_method}"
    .btn-group
      - Order.statuses.keys.each do |status|
        = link_to t("activerecord.attributes.order.status.#{status}"), admin_orders_path(filter_params(status: status)), class: "btn btn-default#{' active' if params[:status] == status}"

  - if @orders.any?
    table.table.orders-list.table-striped.table-hover
      thead
        tr
          th Номер
          th Дата создания
          th Статус
          th Покупатель
          th Сумма
          th Способ оплаты
      tbody
      - @orders.each do |order|
        tr.item
          td
            = link_to order.number, [:admin, order]
          td = l order.created_at, format: :long
          td = order_status order
          td = order.user_name
          td = number_to_currency order.total
          td = order_payment_method order
  - else
    br
    br
    .alert.alert-warning нет заказов

  = paginate @orders, window: 2

app/views/admin/orders/show.html.slim
= render layout: 'boxed', locals: {title: "Заказ № #{@order.number}"} do

  .well
    p
      i.fa.fa-calendar>
      = l @order.created_at, format: :long
    p
      = order_payment_method @order
      = order_status @order
    p = "#{@order.user_name} #{@order.user_phone} #{@order.user.email}"
    p = @order.notes

  table.table.orders-list.table-striped.table-hover
    thead
      tr
        th Наименование
        th Количество
        th Сумма
    tbody
      - @order.suborders.each do |suborder|
        tr
          td
            => link_to suborder.variant.title, suborder.variant.product
            - if suborder.variant.available
              br
              = simple_form_for [:admin, suborder], html: { class: "form-inline" } do |f|
                = f.hidden_field :variant_unavailable, value: true
                = f.button :submit, class: "btn btn-sm btn-default", value: "уведомить об отсутствии"
            - else
              span.label.label-default нет в наличии
          td = suborder.quantity
          td
            s => number_to_currency(suborder.subtotal) if suborder.discount > 0
            = number_to_currency suborder.total

  .text-right
    p => "Коррекция суммы: #{number_to_currency @order.total_correction}" if @order.total_correction != 0
    p => "Комиссия: #{number_to_currency @order.commission}" if @order.commission > 0
    p: strong = "Всего: #{number_to_currency @order.total}"

  .row
    .col-md-4
      / Refactoring..
      - if @order.placed? || @order.pending?
        h5 Изменить статус заказа
        - if @order.placed?
          = simple_form_for [:admin, @order], html: { class: "form-inline" } do |f|
            = f.hidden_field :status, value: :pending
            = f.button :submit, class: "btn btn-info", value: "Заказ в обработке"
        - if @order.pending?
          = simple_form_for [:admin, @order], html: { class: "form-inline" } do |f|
            = f.hidden_field :status, value: :refunded
            = f.button :submit, class: "btn btn-warning", value: "Отменить заказ"
          = simple_form_for [:admin, @order], html: { class: "form-inline" } do |f|
            = f.hidden_field :status, value: :paid
            = f.button :submit, class: "btn btn-success", value: "Заказ оплачен"

    .col-md-8.text-right
      - if @order.placed? || @order.pending?
        = simple_form_for [:admin, @order], html: { class: "form-inline" } do |f|
          = f.hidden_field :status, value: :pending
          = f.input :total_correction, label: "Коррекция суммы", input_html: { style: "width: 100px" }
          = f.button :submit, class: "btn btn-info", value: @order.liqpay? ? "Отправить ссылку для оплаты" : "Сохранить"